/**
 * RHMHCP
 * Red Hat Mobile Hot Code Push API
 *
 * OpenAPI spec version: 0.1.0
 * Contact: kxiang@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Rhmhcp);
  }
}(this, function(expect, Rhmhcp) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Rhmhcp.ProjectDeploymentTarget();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ProjectDeploymentTarget', function() {
    it('should create an instance of ProjectDeploymentTarget', function() {
      // uncomment below and update the code to test ProjectDeploymentTarget
      //var instane = new Rhmhcp.ProjectDeploymentTarget();
      //expect(instance).to.be.a(Rhmhcp.ProjectDeploymentTarget);
    });

    it('should have the property uri (base name: "uri")', function() {
      // uncomment below and update the code to test the property uri
      //var instane = new Rhmhcp.ProjectDeploymentTarget();
      //expect(instance).to.be();
    });

    it('should have the property params (base name: "params")', function() {
      // uncomment below and update the code to test the property params
      //var instane = new Rhmhcp.ProjectDeploymentTarget();
      //expect(instance).to.be();
    });

  });

}));
