/**
 * RHMHCP
 * Red Hat Mobile Hot Code Push API
 *
 * OpenAPI spec version: 0.1.0
 * Contact: kxiang@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ProjectDeploymentTarget'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ProjectDeploymentTarget'));
  } else {
    // Browser globals (root is window)
    if (!root.Rhmhcp) {
      root.Rhmhcp = {};
    }
    root.Rhmhcp.Body = factory(root.Rhmhcp.ApiClient, root.Rhmhcp.ProjectDeploymentTarget);
  }
}(this, function(ApiClient, ProjectDeploymentTarget) {
  'use strict';




  /**
   * The Body model module.
   * @module model/Body
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Body</code>.
   * @alias module:model/Body
   * @class
   * @param name {String} Name of the project
   * @param type {module:model/Body.TypeEnum} Type of the project
   */
  var exports = function(name, type) {
    var _this = this;


    _this['name'] = name;
    _this['type'] = type;

  };

  /**
   * Constructs a <code>Body</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Body} obj Optional instance to populate.
   * @return {module:model/Body} The populated <code>Body</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('_id')) {
        obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('deploymentTarget')) {
        obj['deploymentTarget'] = ProjectDeploymentTarget.constructFromObject(data['deploymentTarget']);
      }
    }
    return obj;
  }

  /**
   * @member {String} _id
   */
  exports.prototype['_id'] = undefined;
  /**
   * Name of the project
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * Type of the project
   * @member {module:model/Body.TypeEnum} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {module:model/ProjectDeploymentTarget} deploymentTarget
   */
  exports.prototype['deploymentTarget'] = undefined;


  /**
   * Allowed values for the <code>type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.TypeEnum = {
    /**
     * value: "cordova"
     * @const
     */
    "cordova": "cordova"  };


  return exports;
}));


