/**
 * RHMHCP
 * Red Hat Mobile Hot Code Push API
 *
 * OpenAPI spec version: 0.1.0
 * Contact: kxiang@redhat.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Body', 'model/DeploymentTargetRHMAP', 'model/DeploymentTargetRHMAPHostApp', 'model/InlineResponse200', 'model/Project', 'model/ProjectDeploymentTarget', 'api/ProjectApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Body'), require('./model/DeploymentTargetRHMAP'), require('./model/DeploymentTargetRHMAPHostApp'), require('./model/InlineResponse200'), require('./model/Project'), require('./model/ProjectDeploymentTarget'), require('./api/ProjectApi'));
  }
}(function(ApiClient, Body, DeploymentTargetRHMAP, DeploymentTargetRHMAPHostApp, InlineResponse200, Project, ProjectDeploymentTarget, ProjectApi) {
  'use strict';

  /**
   * Red_Hat_Mobile_Hot_Code_Push_API.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var Rhmhcp = require('index'); // See note below*.
   * var xxxSvc = new Rhmhcp.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new Rhmhcp.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new Rhmhcp.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new Rhmhcp.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 0.1.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Body model constructor.
     * @property {module:model/Body}
     */
    Body: Body,
    /**
     * The DeploymentTargetRHMAP model constructor.
     * @property {module:model/DeploymentTargetRHMAP}
     */
    DeploymentTargetRHMAP: DeploymentTargetRHMAP,
    /**
     * The DeploymentTargetRHMAPHostApp model constructor.
     * @property {module:model/DeploymentTargetRHMAPHostApp}
     */
    DeploymentTargetRHMAPHostApp: DeploymentTargetRHMAPHostApp,
    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200: InlineResponse200,
    /**
     * The Project model constructor.
     * @property {module:model/Project}
     */
    Project: Project,
    /**
     * The ProjectDeploymentTarget model constructor.
     * @property {module:model/ProjectDeploymentTarget}
     */
    ProjectDeploymentTarget: ProjectDeploymentTarget,
    /**
     * The ProjectApi service constructor.
     * @property {module:api/ProjectApi}
     */
    ProjectApi: ProjectApi
  };

  return exports;
}));
